In [1]:
import numpy as np

In [2]:
def ReLu(x):
    return np.maximum(0,x)

In [18]:
x = np.array([-5,-2,-1,0,1,2,5])

In [19]:
print("Original Array:\n",x)
print("Array after ReLu:\n",ReLu(x))

Original Array:
 [-5 -2 -1  0  1  2  5]
Array after ReLu:
 [0 0 0 0 1 2 5]


# ReLu Derivative

In [25]:
def ReLu_Derivative(x):
    return (x > 0).astype(float)

In [28]:
x = np.array([-5,-2,-1,0,1,2,5])
print("ReLu Derivative:\n", ReLu_Derivative(x))

ReLu Derivative:
 [0. 0. 0. 0. 1. 1. 1.]
